# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 475ae1ad3b50a00e1ff443020ded78fe8d2a17380ad4b88dae2b41f732f23321b8761e6513649c60b3835193b998d09c61801f2ae410ec530625c8246ab10f77

test:
  secret_key_base: 8c7db629c73107d184c60f20624a89b556271c457011250de0339df54d7de1426815a25eb0dfd87bbd8f8148a2ad2c35db69547075da91e5d9570a452fe2d1d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
